### ISSUE TITLE
Api search Azuracast

### ISSUE THREAD

**Issue by RafaelTunes** [joeyboli/MusicInfoAPI#1]
My friend, this helped me a lot, but it is possible for art to come from azuracast, because the deezer spotify and tunes api come with wrong covers on my radio station. Thanks

**Comment by joeyboli** [comment]
i can parse the azuracast now playing api for you. but where do you want to use it ?

**Comment by RafaelTunes** [comment]
oops, on my player https://onbeat.top/estacao-2000s/

**Comment by RafaelTunes** [comment]
and those html5 player https://github.com/gsavio/player-shoutcast-html5  thnks

**Comment by RafaelTunes** [comment]
I use it on one of the radio channels here https://onbeat.top/canais/2000/

**Comment by joeyboli** [comment]
> I use it on one of the radio channels here https://onbeat.top/canais/2000/

i just opened it a
![f20af892-2a34-49b7-987c-4697e14a2357](https://github.com/joeyboli/MusicInfoAPI/assets/43940776/b15eb18a-0ad5-4752-b07f-51c9982e8dfa)
nd this is what i see.

**Comment by joeyboli** [comment]
also i noticed your stream keeps breaking here and there. you use contabo which is a worse vps service for streaming.

**Comment by RafaelTunes** [comment]
the account is the worst, they recommended it to me :(

**Comment by joeyboli** [comment]
> the account is the worst, they recommended it to me :(

i just added azuracast support to the search api. edit the file and change apitype to azuracast and then put in your now playing azuracast url in line 21

**Comment by RafaelTunes** [comment]
my friend can you tell me no that contabo is that bad

**Comment by joeyboli** [comment]
i used it first for azuracast and it was horrible. id recommend you check out hetzner

**Comment by RafaelTunes** [comment]
Thank you very much, you helped me a lot with the players and the api, I don't know how to repay you

**Comment by joeyboli** [comment]
haha dont worry about it.

**Comment by RafaelTunes** [comment]
thank you very much, I wish you much success in your life, you deserve it, you are a good person. Congratulations on the works

**Comment by joeyboli** [comment]
> thank you very much, I wish you much success in your life, you deserve it, you are a good person. Congratulations on the works

:)

**Comment by RafaelTunes** [comment]
the art does not appear :/

**Comment by RafaelTunes** [comment]
it returns like this, if you remove the bars it works https://onbeat.link//api//station//2//art//a3cc6806de991a1cd495583e-1685372281.jpg

**Comment by joeyboli** [comment]
can i see where you run it ?

**Comment by RafaelTunes** [comment]
sorry, it must be the script.js, the api is working but the art is not. I made a mess hahaha, I don't understand very well, I still scrambled everything

**Comment by joeyboli** [comment]
when i run it here i get

 `{
"artist": "Rihanna",
"title": "Don't Stop The Music",
"artwork": "https://onbeat.link/api/station/2/art/4743c74e8e8e63d14cf42175-1685041541.jpg"
}`

**Comment by RafaelTunes** [comment]
https://onbeat.top/canais/2000/2000.zip where is in 'api' folder

**Comment by joeyboli** [comment]
okay.

**Comment by RafaelTunes** [comment]
here in the player only the name of the song and the artist appears, not the art. If I go back to 'deezer' in the api it goes back to art

**Comment by joeyboli** [comment]
okay let me test on my side and i will let you know how it goes

**Comment by joeyboli** [comment]
so i did test and all i see is a white page.

**Comment by RafaelTunes** [comment]
ela aparece em branco se deixar azuracast se colocar deezer na pasta api aparece a img

**Comment by RafaelTunes** [comment]
it appears blank because it doesn't come with the background and cover art, but if you select it on the page you can see that the names are there. Friend, don't worry, I don't think it works, in my case because I modified so many things that I don't remember, I think the problem is in the script.js. But thanks for all the help, don't worry you've already done a lot and I appreciate it

**Comment by joeyboli** [comment]
do not worry. i am currently modifying [https://github.com/joeyboli/html5-shoutcast-icecast-zeno-player/](url) to add support to every stream url out there so worry less.

**Comment by joeyboli** [comment]
just keep an eye on it

**Comment by RafaelTunes** [comment]
OK thanks

**Comment by RafaelTunes** [comment]
and that now I was worried about the account, I have to see how to solve it :(

**Comment by joeyboli** [comment]
haha leave it to me :)

**Comment by joeyboli** [comment]
hey, redownload the api code. i forgot to add the results array added it and it should work fine now

**Comment by RafaelTunes** [comment]
now it worked here :)

**Comment by RafaelTunes** [comment]
thank you very much

**Comment by joeyboli** [comment]
sure, enjoy.
